import type { Candidate } from "./types";

export const candidates: Candidate[] = [
  ["Avery Chen","Climate operations leader","Turns complex programs into clear systems.","Approved their profile to make career pivots more visible.","Medium",[["Program Manager","clean-energy infrastructure","2022–now","Built an operator playbook for regional charging deployments."],["Operations Lead","urban mobility","2020–22","Launched reliability programs across shared transit partners."],["Analyst","public-interest consulting","2018–20","Modeled how cities could reduce commute emissions."]]],
  ["Mara Ellis","Product designer","Designs calm tools for busy people.","Opted in to celebrate nonlinear creative careers.","Easy",[["Senior Product Designer","health technology","2023–now","Designed care-planning workflows with clinicians."],["Product Designer","financial education","2020–23","Made first-time investing concepts easier to understand."],["Visual Designer","community media","2018–20","Created editorial systems for local stories."]]],
  ["Noah Patel","Data storyteller","Finds the human signal in operational data.","Wanted to show that analytical careers can be generous.","Hard",[["Analytics Manager","food systems nonprofit","2022–now","Built reporting tools for food-rescue partners."],["Data Scientist","consumer research","2020–22","Translated behavior studies into product decisions."],["Research Associate","public policy lab","2018–20","Evaluated access to public benefits."]]],
  ["Jordan Reyes","Community builder","Connects people to practical opportunity.","Approved a deck with only self-selected experiences.","Easy",[["Partnerships Director","workforce development","2023–now","Developed employer pathways for career changers."],["Program Manager","higher education","2020–23","Led peer mentoring for transfer students."],["Organizer","neighborhood nonprofit","2018–20","Coordinated volunteer-led mutual-aid programs."]]],
  ["Leila Morgan","Security engineer","Makes trust an everyday product feature.","Enjoys the game because it rewards curiosity, not credentials.","Hard",[["Security Engineer","collaboration software","2022–now","Improved access-control reviews for distributed teams."],["Software Engineer","civic technology","2020–22","Built resilient intake systems for public services."],["Technical Fellow","digital rights nonprofit","2019–20","Researched safer authentication patterns."]]],
  ["Theo Brooks","Brand strategist","Builds brands with a point of view.","Chose to share an approved, high-level timeline.","Medium",[["Brand Strategy Lead","consumer goods","2023–now","Guided launches for low-waste home products."],["Strategist","creative studio","2020–23","Developed positioning for mission-led founders."],["Writer","independent publication","2018–20","Reported on the changing nature of work."]]],
  ["Iris Park","Learning designer","Makes hard ideas feel learnable.","Opted in to normalize careers across education and tech.","Medium",[["Learning Experience Lead","developer education","2022–now","Created hands-on courses for emerging builders."],["Instructional Designer","online learning","2020–22","Shaped accessible course systems for adults."],["Teacher","public education","2017–20","Taught interdisciplinary humanities."]]],
  ["Samir Okafor","Supply chain planner","Keeps good things moving.","Participates with anonymized experience descriptions only.","Hard",[["Planning Manager","circular retail","2023–now","Reduced excess inventory through demand signals."],["Operations Analyst","consumer logistics","2020–23","Modeled regional fulfillment capacity."],["Coordinator","food distribution","2018–20","Supported delivery operations for local producers."]]],
  ["Priya Shah","People operations partner","Designs kinder systems of work.","Approved their career card after reviewing every clue.","Easy",[["People Partner","social enterprise","2022–now","Created manager practices for sustainable teams."],["Talent Programs Lead","technology services","2020–22","Built early-career development programs."],["Recruiting Coordinator","creative agency","2018–20","Improved candidate communication systems."]]],
  ["Elliot Grant","Researcher","Studies how institutions earn trust.","Wanted a playful way to share a research path.","Hard",[["Research Lead","public-interest technology","2023–now","Studied how people navigate automated decisions."],["Policy Researcher","consumer advocacy","2020–23","Published plain-language evidence briefs."],["Research Assistant","university lab","2018–20","Supported participatory community studies."]]],
  ["Camille Laurent","Service designer","Improves the moments between systems.","Joined to make service design careers more legible.","Medium",[["Service Design Lead","public health","2023–now","Mapped patient handoffs across care settings."],["Experience Designer","financial services","2020–23","Redesigned support journeys for life events."],["Design Researcher","innovation studio","2018–20","Led interviews for civic services."]]],
  ["Ben Ortiz","Growth operator","Builds durable habits, not vanity metrics.","Contributed a career path focused on learning in public.","Medium",[["Growth Lead","responsible commerce","2022–now","Tested retention programs for independent makers."],["Product Marketing Manager","small-business software","2020–22","Launched tools for neighborhood businesses."],["Account Manager","media technology","2018–20","Helped local publishers adopt new workflows."]]],
  ["Nadia Bell","Accessibility specialist","Advocates for products everyone can use.","Opted in with deliberately generalized employers and dates.","Easy",[["Accessibility Program Manager","consumer technology","2023–now","Embedded inclusive design reviews into launches."],["UX Researcher","digital government","2020–23","Tested accessible journeys for public services."],["Advocate","disability nonprofit","2018–20","Ran digital inclusion workshops."]]],
  ["Rowan Kim","Finance lead","Helps mission-led teams make room to grow.","Chose this deck to demystify operations careers.","Hard",[["Finance & Operations Director","arts nonprofit","2022–now","Built planning tools for multi-year programs."],["Financial Analyst","impact investing","2020–22","Assessed operating models for small enterprises."],["Bookkeeper","community business","2018–20","Supported independent creative teams."]]],
  ["Zoe Hart","Editorial producer","Makes ambitious ideas approachable.","Approved a concise experience deck, not a public profile.","Medium",[["Editorial Director","science communication","2023–now","Commissioned explainers about emerging research."],["Producer","audio journalism","2020–23","Produced a weekly show about work and culture."],["Editor","independent magazine","2018–20","Edited profiles of local innovators."]]]
].map(([name,headline,bio,why,difficulty,rows], index) => ({ id: `seed-${index + 1}`, name: name as string, headline: headline as string, bio: bio as string, why: why as string, difficulty: difficulty as Candidate["difficulty"], photoApproved: false, experiences: (rows as string[][]).map((r,i) => ({ id: `e-${index}-${i}`, role:r[0], category:r[1], period:r[2], description:r[3] })) }));

export const getCandidate = (id: string) => candidates.find(c => c.id === id) ?? candidates[0];
