-- Consent-first schema. Run with `supabase db reset` locally.
create type public.user_role as enum ('player','admin');
create type public.round_status as enum ('active','won','revealed','abandoned');
create table public.users (id uuid primary key references auth.users(id) on delete cascade, role public.user_role not null default 'player', created_at timestamptz not null default now());
create table public.player_profiles (id uuid primary key references public.users(id) on delete cascade, display_name text not null check (char_length(display_name) between 2 and 80), approved_bio text, approved_photo_url text, deleted_at timestamptz, created_at timestamptz not null default now());
create table public.profile_consent_settings (profile_id uuid primary key references public.player_profiles(id) on delete cascade, participation_enabled boolean not null default false, show_photo_after_reveal boolean not null default false, use_short_bio boolean not null default false, include_daily_challenges boolean not null default false, approved_at timestamptz, updated_at timestamptz not null default now());
create table public.career_experiences (id uuid primary key default gen_random_uuid(), profile_id uuid not null references public.player_profiles(id) on delete cascade, role_title text not null, employer_category text not null, date_range text not null, approved_description text, excluded_from_game boolean not null default false, approved_at timestamptz, created_at timestamptz not null default now());
create table public.game_decks (id uuid primary key default gen_random_uuid(), profile_id uuid not null references public.player_profiles(id), status text not null default 'draft' check (status in ('draft','approved','archived')), created_at timestamptz not null default now());
create table public.game_rounds (id uuid primary key default gen_random_uuid(), player_id uuid not null references public.users(id), deck_id uuid not null references public.game_decks(id), clue_index smallint not null default 0 check (clue_index between 0 and 3), score_awarded integer not null default 0, status public.round_status not null default 'active', completed_at timestamptz, unique(player_id, deck_id));
create table public.round_guesses (id uuid primary key default gen_random_uuid(), round_id uuid not null references public.game_rounds(id) on delete cascade, guessed_profile_id uuid not null references public.player_profiles(id), is_correct boolean not null default false, created_at timestamptz not null default now());
create table public.daily_challenges (challenge_date date primary key, deck_id uuid not null references public.game_decks(id), created_at timestamptz not null default now());
create table public.leaderboard_snapshots (id uuid primary key default gen_random_uuid(), week_start date not null, player_id uuid not null references public.users(id), score integer not null, rank integer not null, unique(week_start,player_id));
alter table public.users enable row level security; alter table public.player_profiles enable row level security; alter table public.profile_consent_settings enable row level security; alter table public.career_experiences enable row level security; alter table public.game_rounds enable row level security; alter table public.round_guesses enable row level security;
create policy "users read self" on public.users for select using (auth.uid()=id);
create policy "profile own read" on public.player_profiles for select using (auth.uid()=id); create policy "profile own write" on public.player_profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy "consent own" on public.profile_consent_settings for all using (auth.uid()=profile_id) with check (auth.uid()=profile_id);
create policy "experiences own" on public.career_experiences for all using (auth.uid()=profile_id) with check (auth.uid()=profile_id);
create policy "rounds own" on public.game_rounds for select using (auth.uid()=player_id);
create policy "guesses own round" on public.round_guesses for select using (exists(select 1 from public.game_rounds r where r.id=round_id and r.player_id=auth.uid()));
-- Decks and candidates intentionally have no client SELECT policy. Server RPCs must return only anonymized clues until resolution.
